In [7]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:75% !important; }</style>"))

In [25]:
import sys
import numpy as np
import pandas as pd

sys.path.append('/lfs/1/sahaana/enrichment/ember/utils')
from knn_utils import bm25_imdb_wiki_recall, compute_top_k_pd, bm25_SQuAD_sent_recall, bm25_imdb_fuzzy_recall, bm25_deepmatcher_recall


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
path = "/lfs/1/sahaana/enrichment/data/Okapi25Queries"
merged_col = "merged_all"

# SQuAD

## Sent

In [24]:
file = "dev_SQuAD_sent"

bm25 = pd.read_pickle(f"{path}/{file}_argsort_indices.pkl")

supervision = '/lfs/1/sahaana/enrichment/data/SQuAD/dev_sent_labels.pkl'
supervision = pd.read_pickle(supervision)
supervision

        QID       SID
0     86821  [228945]
1     86822  [228945]
2     86823  [228947]
3     86824  [228947]
4     86825  [228951]
...     ...       ...
5923  92744  [244298]
5924  92745  [244298]
5925  92746  [244300]
5926  92747  [244304]
5927  92748  [244304]

[5928 rows x 2 columns]

In [32]:
compute_top_k_pd(bm25_SQuAD_sent_recall, (bm25, supervision), k_max=30)

k: 1 	 avg: 0.5334120823489706 	 count: 3161 	 MRR: 0.5334120823489706
k: 2 	 avg: 0.6029362132973338 	 count: 3573 	 MRR: 0.5681741478231522
k: 3 	 avg: 0.6339858251771853 	 count: 3757 	 MRR: 0.5785240184497693
k: 4 	 avg: 0.6557543030712116 	 count: 3886 	 MRR: 0.5839661379232759
k: 5 	 avg: 0.6714478569017888 	 count: 3979 	 MRR: 0.5871048486893914
k: 6 	 avg: 0.6819102261221734 	 count: 4041 	 MRR: 0.5888485768927888
k: 7 	 avg: 0.6928788390145123 	 count: 4106 	 MRR: 0.5904155215916943
k: 8 	 avg: 0.7021599730003375 	 count: 4161 	 MRR: 0.5915756633399225
k: 9 	 avg: 0.7085723928450894 	 count: 4199 	 MRR: 0.5922881544337839
k: 10 	 avg: 0.7153223084711441 	 count: 4239 	 MRR: 0.5929631459963892
k: 11 	 avg: 0.7219034762065474 	 count: 4278 	 MRR: 0.5935614339723351
k: 12 	 avg: 0.7294971312858589 	 count: 4323 	 MRR: 0.5941942385622777
k: 13 	 avg: 0.7345595680053999 	 count: 4353 	 MRR: 0.5945836567714732
k: 14 	 avg: 0.7408032399595005 	 count: 4390 	 MRR: 0.5950296333396232
k: 15 	 avg: 0.7462031724603443 	 count: 4422 	 MRR: 0.5953896288396794
k: 16 	 avg: 0.7499156260546743 	 count: 4444 	 MRR: 0.595621657189325
k: 17 	 avg: 0.7532905838677016 	 count: 4464 	 MRR: 0.5958201841195031
k: 18 	 avg: 0.7571717853526831 	 count: 4487 	 MRR: 0.5960358064242243
k: 19 	 avg: 0.7605467431657105 	 count: 4507 	 MRR: 0.5962134357828047
k: 20 	 avg: 0.7637529530880864 	 count: 4526 	 MRR: 0.5963737462789236
k: 21 	 avg: 0.7688153898076274 	 count: 4556 	 MRR: 0.5966148146941398
k: 22 	 avg: 0.7721903476206547 	 count: 4576 	 MRR: 0.5967682218674593
k: 23 	 avg: 0.7753965575430307 	 count: 4595 	 MRR: 0.5969076222988668
k: 24 	 avg: 0.778265271684104 	 count: 4612 	 MRR: 0.597027152054745
k: 25 	 avg: 0.7824839689503881 	 count: 4637 	 MRR: 0.5971958999453963
k: 26 	 avg: 0.7863651704353696 	 count: 4660 	 MRR: 0.5973451769255879
k: 27 	 avg: 0.7887276409044887 	 count: 4674 	 MRR: 0.5974326758318516
k: 28 	 avg: 0.7912588592642592 	 count: 4689 	 MRR: 0.5975230764875576
k: 29 	 avg: 0.7936213297333783 	 count: 4703 	 MRR: 0.5976045409864927
k: 30 	 avg: 0.7958150523118461 	 count: 4716 	 MRR: 0.5976776650724417

,k,avg,count,MRR,results,MRR_results
0,1,0.533412,3161,0.533412,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,2,0.602936,3573,0.568174,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,3,0.633986,3757,0.578524,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,4,0.655754,3886,0.583966,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,5,0.671448,3979,0.587105,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,6,0.681910,4041,0.588849,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6,7,0.692879,4106,0.590416,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
7,8,0.702160,4161,0.591576,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
8,9,0.708572,4199,0.592288,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
9,10,0.715322,4239,0.592963,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
10,11,0.721903,4278,0.593561,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
11,12,0.729497,4323,0.594194,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
12,13,0.734560,4353,0.594584,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
13,14,0.740803,4390,0.595030,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
14,15,0.746203,4422,0.595390,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
15,16,0.749916,4444,0.595622,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
16,17,0.753291,4464,0.595820,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
17,18,0.757172,4487,0.596036,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
18,19,0.760547,4507,0.596213,"[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.0, 0.125, 0.0, 0.0, 0.125, 0..."
19,20,0.763753,4526,0.596374,"[0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0, 0.125, ..."
20,21,0.768815,4556,0.596615,"[0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0, 0.125, ..."
21,22,0.772190,4576,0.596768,"[0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0, 0.125, ..."
22,23,0.775397,4595,0.596908,"[0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0434782608..."
23,24,0.778265,4612,0.597027,"[0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0434782608..."
24,25,0.782484,4637,0.597196,"[0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0434782608..."
25,26,0.786365,4660,0.597345,"[0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0434782608..."
26,27,0.788728,4674,0.597433,"[0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0434782608..."
27,28,0.791259,4689,0.597523,"[0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0434782608..."
28,29,0.793621,4703,0.597605,"[0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0434782608..."
29,30,0.795815,4716,0.597678,"[0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, ...","[0.0, 1.0, 0.0, 0.05, 0.125, 0.0, 0.0434782608..."

## Para

In [12]:
file = "dev_SQuAD_para"

bm25 = pd.read_pickle(f"{path}/{file}_argsort_indices.pkl")

supervision = '/lfs/1/sahaana/enrichment/data/SQuAD/dev_para_labels.pkl'
supervision = pd.read_pickle(supervision)
supervision

        QID    PID
0     86821  19035
1     86822  19035
2     86823  19035
3     86824  19035
4     86825  19035
...     ...    ...
5923  92744  20238
5924  92745  20238
5925  92746  20238
5926  92747  20238
5927  92748  20238

[5928 rows x 2 columns]

In [14]:
for k in range(1,31):
    avg, count, MRR, results, MRR_results = bm25_SQuAD_recall(bm25, supervision, mode="PID", k=k)
    print(f"k: {k} \t avg: {avg} \t count: {count} \t MRR: {MRR}")

k: 1 	 avg: 0.6144110698616267 	 count: 3641 	 MRR: 0.6144110698616267
k: 2 	 avg: 0.7041849476881539 	 count: 4173 	 MRR: 0.6592980087748903
k: 3 	 avg: 0.744684441444482 	 count: 4413 	 MRR: 0.6727978400269997
k: 4 	 avg: 0.7649341883226459 	 count: 4533 	 MRR: 0.6778602767465407
k: 5 	 avg: 0.7824839689503881 	 count: 4637 	 MRR: 0.6813702328720891
k: 6 	 avg: 0.7966587917651029 	 count: 4721 	 MRR: 0.6837327033412082
k: 7 	 avg: 0.8052649341883227 	 count: 4772 	 MRR: 0.684962152258811
k: 8 	 avg: 0.8133648329395883 	 count: 4820 	 MRR: 0.6859746396027192
k: 9 	 avg: 0.8228147148160648 	 count: 4876 	 MRR: 0.6870246264778833
k: 10 	 avg: 0.8327708403644954 	 count: 4935 	 MRR: 0.6880202390327265
k: 11 	 avg: 0.8405332433344583 	 count: 4981 	 MRR: 0.6887259120299958
k: 12 	 avg: 0.845933175835302 	 count: 5013 	 MRR: 0.689175906405066
k: 13 	 avg: 0.8528518393520081 	 count: 5054 	 MRR: 0.6897081112909664
k: 14 	 avg: 0.8580830239622005 	 count: 5085 	 MRR: 0.6900817673345516
k: 15 	 avg: 0.8636517043536955 	 count: 5118 	 MRR: 0.6904530126939846
k: 16 	 avg: 0.8668579142760715 	 count: 5137 	 MRR: 0.6906534008141332
k: 17 	 avg: 0.870739115761053 	 count: 5160 	 MRR: 0.690881706783838
k: 18 	 avg: 0.8746203172460344 	 count: 5183 	 MRR: 0.6910973290885591
k: 19 	 avg: 0.8771515356058049 	 count: 5198 	 MRR: 0.6912305511074943
k: 20 	 avg: 0.8800202497468782 	 count: 5215 	 MRR: 0.6913739868145481
k: 21 	 avg: 0.8827202159973 	 count: 5231 	 MRR: 0.6915025566359967
k: 22 	 avg: 0.8842389470131623 	 count: 5240 	 MRR: 0.6915715898639906
k: 23 	 avg: 0.8866014174822815 	 count: 5254 	 MRR: 0.6916743059713435
k: 24 	 avg: 0.8903138710766115 	 count: 5276 	 MRR: 0.691828991537774
k: 25 	 avg: 0.8945325683428957 	 count: 5301 	 MRR: 0.6919977394284254
k: 26 	 avg: 0.8962200472494094 	 count: 5311 	 MRR: 0.6920626424632912
k: 27 	 avg: 0.8987512656091798 	 count: 5326 	 MRR: 0.6921563912914309
k: 28 	 avg: 0.9001012487343908 	 count: 5334 	 MRR: 0.692204604974474
k: 29 	 avg: 0.901113736078299 	 count: 5340 	 MRR: 0.6922395183311605
k: 30 	 avg: 0.9034762065474181 	 count: 5354 	 MRR: 0.6923182673467978

# imdb_wiki

## Testing on the train data

In [12]:
file = "imdb_wiki"

bm25 = pd.read_pickle(f"{path}/{file}_argsort_indices.pkl")

supervision = f'/lfs/1/sahaana/enrichment/data/{file}/supervision_train.pkl'
supervision = pd.read_pickle(supervision)
supervision

         IMDB_ID        QID
41098  tt2825120  Q14639047
28950  tt0403455   Q2120775
29297  tt0418460   Q3413700
30720  tt0477139   Q2002073
24124  tt0189630   Q3191800
...          ...        ...
23176  tt0154420    Q841958
47758  tt9358106  Q64768058
46228  tt6284256  Q77733171
32823  tt0997274   Q1037699
23808  tt0175996    Q590308

[38250 rows x 2 columns]

In [15]:
for k in range(1,31):
    avg, count, MRR, results, MRR_results = bm25_imdb_wiki_recall(bm25, supervision, k=k)
    print(f"k: {k} \t avg: {avg} \t count: {count} \t MRR: {MRR}")

k: 1 	 avg: 0.6769934640522876 	 count: 25895 	 MRR: 0.6769934640522876
k: 2 	 avg: 0.769281045751634 	 count: 29425 	 MRR: 0.7231372549019608
k: 3 	 avg: 0.8038169934640523 	 count: 30746 	 MRR: 0.7346492374727669
k: 4 	 avg: 0.825673202614379 	 count: 31582 	 MRR: 0.7401132897603484
k: 5 	 avg: 0.8414901960784313 	 count: 32187 	 MRR: 0.7432766884531592
k: 6 	 avg: 0.8542483660130719 	 count: 32675 	 MRR: 0.7454030501089325
k: 7 	 avg: 0.8634509803921568 	 count: 33027 	 MRR: 0.7467177093059446
k: 8 	 avg: 0.8709019607843137 	 count: 33312 	 MRR: 0.7476490818549643
k: 9 	 avg: 0.8782483660130719 	 count: 33593 	 MRR: 0.748465349102604
k: 10 	 avg: 0.8847581699346405 	 count: 33842 	 MRR: 0.7491163294947608
k: 11 	 avg: 0.8906928104575164 	 count: 34069 	 MRR: 0.7496558422695678
k: 12 	 avg: 0.8952941176470588 	 count: 34245 	 MRR: 0.750039284535363
k: 13 	 avg: 0.9003137254901961 	 count: 34437 	 MRR: 0.7504254082156044
k: 14 	 avg: 0.9046797385620915 	 count: 34604 	 MRR: 0.7507372662921682
k: 15 	 avg: 0.9083398692810457 	 count: 34744 	 MRR: 0.7509812750067651
k: 16 	 avg: 0.9122091503267974 	 count: 34892 	 MRR: 0.7512231050721246
k: 17 	 avg: 0.9155032679738562 	 count: 35018 	 MRR: 0.7514168766984223
k: 18 	 avg: 0.918718954248366 	 count: 35141 	 MRR: 0.7515955259358951
k: 19 	 avg: 0.9212549019607843 	 count: 35238 	 MRR: 0.7517289968681276
k: 20 	 avg: 0.9235555555555556 	 count: 35326 	 MRR: 0.7518440295478661
k: 21 	 avg: 0.9258823529411765 	 count: 35415 	 MRR: 0.7519548294233719
k: 22 	 avg: 0.9280522875816993 	 count: 35498 	 MRR: 0.752053462816123
k: 23 	 avg: 0.9300653594771242 	 count: 35575 	 MRR: 0.7521409876811415
k: 24 	 avg: 0.9321045751633987 	 count: 35653 	 MRR: 0.7522259550014029
k: 25 	 avg: 0.9340915032679739 	 count: 35729 	 MRR: 0.7523054321255858
k: 26 	 avg: 0.9363137254901961 	 count: 35814 	 MRR: 0.7523909022110559
k: 27 	 avg: 0.9383790849673203 	 count: 35893 	 MRR: 0.752467397006505
k: 28 	 avg: 0.9398692810457516 	 count: 35950 	 MRR: 0.7525206182950203
k: 29 	 avg: 0.9415947712418301 	 count: 36016 	 MRR: 0.7525801179569541
k: 30 	 avg: 0.9430588235294117 	 count: 36072 	 MRR: 0.7526289196998733

## dev data

In [36]:
file = "imdb_wiki"

bm25 = pd.read_pickle(f"{path}/dev_{file}_argsort_indices.pkl")

supervision = f'/lfs/1/sahaana/enrichment/data/{file}/supervision_test.pkl'
supervision = pd.read_pickle(supervision)
supervision

         IMDB_ID        QID
4026   tt0038427    Q547323
36696  tt1613092   Q5652429
35072  tt1327820    Q992227
45272  tt5462602  Q24901880
6080   tt0047167   Q1091180
...          ...        ...
9398   tt0060865    Q323820
14428  tt0081111   Q6748794
29105  tt0410400   Q3549360
19690  tt0107611   Q2525108
18937  tt0103128   Q1198774

[9563 rows x 2 columns]

In [39]:
compute_top_k_pd(bm25_imdb_wiki_recall, (bm25, supervision), k_max=30)

k: 1 	 avg: 0.6325420893025201 	 count: 6049 	 MRR: 0.6325420893025201
k: 2 	 avg: 0.861863431977413 	 count: 8242 	 MRR: 0.7472027606399665
k: 3 	 avg: 0.8995085224301997 	 count: 8602 	 MRR: 0.7597511241242287
k: 4 	 avg: 0.918853916135104 	 count: 8787 	 MRR: 0.7645874725504548
k: 5 	 avg: 0.9310885705322598 	 count: 8904 	 MRR: 0.7670344034298859
k: 6 	 avg: 0.9406044128411586 	 count: 8995 	 MRR: 0.7686203771480358
k: 7 	 avg: 0.9499111157586532 	 count: 9084 	 MRR: 0.7699499061362493
k: 8 	 avg: 0.9558715884136777 	 count: 9141 	 MRR: 0.7706949652181273
k: 9 	 avg: 0.9605772247202761 	 count: 9186 	 MRR: 0.7712178136966383
k: 10 	 avg: 0.9624594792429154 	 count: 9204 	 MRR: 0.7714060391489024
k: 11 	 avg: 0.9647600125483635 	 count: 9226 	 MRR: 0.7716151785403066
k: 12 	 avg: 0.9668514064624072 	 count: 9246 	 MRR: 0.771789461366477
k: 13 	 avg: 0.9694656488549618 	 count: 9271 	 MRR: 0.7719905569351351
k: 14 	 avg: 0.9704067761162815 	 count: 9280 	 MRR: 0.7720577803109435
k: 15 	 avg: 0.9719753215518143 	 count: 9295 	 MRR: 0.7721623500066457
k: 16 	 avg: 0.9731255882045383 	 count: 9306 	 MRR: 0.7722342416724409
k: 17 	 avg: 0.9736484366830492 	 count: 9311 	 MRR: 0.7722649974652945
k: 18 	 avg: 0.9750078427271777 	 count: 9324 	 MRR: 0.7723405200233017
k: 19 	 avg: 0.9758444002927952 	 count: 9332 	 MRR: 0.7723845493688605
k: 20 	 avg: 0.9767855275541149 	 count: 9341 	 MRR: 0.7724316057319265
k: 21 	 avg: 0.9776220851197323 	 count: 9349 	 MRR: 0.7724714418064798
k: 22 	 avg: 0.978040363902541 	 count: 9353 	 MRR: 0.7724904544784256
k: 23 	 avg: 0.9781449335982433 	 count: 9354 	 MRR: 0.7724950009869344
k: 24 	 avg: 0.9788769214681585 	 count: 9361 	 MRR: 0.7725255004815141
k: 25 	 avg: 0.9790860608595628 	 count: 9363 	 MRR: 0.7725338660571703
k: 26 	 avg: 0.9793997699466694 	 count: 9366 	 MRR: 0.7725459317912898
k: 27 	 avg: 0.9801317578165848 	 count: 9373 	 MRR: 0.7725730424531385
k: 28 	 avg: 0.9807591759907979 	 count: 9379 	 MRR: 0.7725954502450747
k: 29 	 avg: 0.9809683153822022 	 count: 9381 	 MRR: 0.7726026619482266
k: 30 	 avg: 0.9811774547736066 	 count: 9383 	 MRR: 0.7726096332612734

,k,avg,count,MRR,results,MRR_results
0,1,0.632542,6049,0.632542,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, ...","[1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, ..."
1,2,0.861863,8242,0.747203,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, ..."
2,3,0.899509,8602,0.759751,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, ..."
3,4,0.918854,8787,0.764587,"[1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, ..."
4,5,0.931089,8904,0.767034,"[1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.0, 1.0, 1.0, 1.0, 0.2, 1.0, 1.0, 1.0, ..."
5,6,0.940604,8995,0.768620,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
6,7,0.949911,9084,0.769950,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
7,8,0.955872,9141,0.770695,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
8,9,0.960577,9186,0.771218,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
9,10,0.962459,9204,0.771406,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
10,11,0.964760,9226,0.771615,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
11,12,0.966851,9246,0.771789,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
12,13,0.969466,9271,0.771991,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
13,14,0.970407,9280,0.772058,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
14,15,0.971975,9295,0.772162,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
15,16,0.973126,9306,0.772234,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
16,17,0.973648,9311,0.772265,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
17,18,0.975008,9324,0.772341,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
18,19,0.975844,9332,0.772385,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
19,20,0.976786,9341,0.772432,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
20,21,0.977622,9349,0.772471,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
21,22,0.978040,9353,0.772490,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
22,23,0.978145,9354,0.772495,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
23,24,0.978877,9361,0.772526,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
24,25,0.979086,9363,0.772534,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
25,26,0.979400,9366,0.772546,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
26,27,0.980132,9373,0.772573,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
27,28,0.980759,9379,0.772595,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
28,29,0.980968,9381,0.772603,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."
29,30,0.981177,9383,0.772610,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1.0, 0.16666666666666666, 1.0, 1.0, 1.0, 0.2,..."

## HARD dev data

In [21]:
file = "imdb_wiki"

bm25 = pd.read_pickle(f"{path}/HARD_dev_{file}_argsort_indices.pkl")

supervision = f'/lfs/1/sahaana/enrichment/data/{file}/HARD_supervision_test.pkl'
supervision = pd.read_pickle(supervision)
supervision

         IMDB_ID        QID
36059  tt1509767    Q309248
665    tt0019735    Q598245
1550   tt0025452    Q506625
44624  tt4940416  Q22674122
33944  tt1174693  Q11187871
...          ...        ...
2195   tt0029297   Q3824951
14823  tt0082905   Q3903060
32290  tt0896529   Q1025973
30498  tt0468521   Q4401668
20074  tt0109903   Q4156443

[9563 rows x 2 columns]

In [22]:
for k in range(1,31):
    avg, count, MRR, results, MRR_results = bm25_imdb_wiki_recall(bm25, supervision, k=k)
    print(f"k: {k} \t avg: {avg} \t count: {count} \t MRR: {MRR}")

k: 1 	 avg: 0.7342884032207466 	 count: 7022 	 MRR: 0.7342884032207466
k: 2 	 avg: 0.833734183833525 	 count: 7973 	 MRR: 0.7840112935271358
k: 3 	 avg: 0.8850779044232981 	 count: 8464 	 MRR: 0.8011258670570601
k: 4 	 avg: 0.9102792010875248 	 count: 8705 	 MRR: 0.8074261912231168
k: 5 	 avg: 0.922827564571787 	 count: 8825 	 MRR: 0.8099358639199694
k: 6 	 avg: 0.9307748614451532 	 count: 8901 	 MRR: 0.8112604133988637
k: 7 	 avg: 0.9396632855798389 	 count: 8986 	 MRR: 0.8125301882752474
k: 8 	 avg: 0.9456237582348636 	 count: 9043 	 MRR: 0.8132752473571254
k: 9 	 avg: 0.9517933702812925 	 count: 9102 	 MRR: 0.8139607598067286
k: 10 	 avg: 0.9568127156749974 	 count: 9150 	 MRR: 0.8144626943460991
k: 11 	 avg: 0.9607863641116804 	 count: 9188 	 MRR: 0.8148239351130703
k: 12 	 avg: 0.9646554428526612 	 count: 9225 	 MRR: 0.8151463583414854
k: 13 	 avg: 0.966746836766705 	 count: 9245 	 MRR: 0.8153072347964118
k: 14 	 avg: 0.9691519397678553 	 count: 9268 	 MRR: 0.8154790278679225
k: 15 	 avg: 0.9705113458119837 	 count: 9281 	 MRR: 0.8155696549375311
k: 16 	 avg: 0.9720798912475165 	 count: 9296 	 MRR: 0.8156676890272518
k: 17 	 avg: 0.9731255882045383 	 count: 9306 	 MRR: 0.815729200612959
k: 18 	 avg: 0.9736484366830492 	 count: 9311 	 MRR: 0.8157582477506541
k: 19 	 avg: 0.9750078427271777 	 count: 9324 	 MRR: 0.8158297954371873
k: 20 	 avg: 0.9759489699884973 	 count: 9333 	 MRR: 0.8158768518002532
k: 21 	 avg: 0.9763672487713061 	 count: 9337 	 MRR: 0.8158967698375299
k: 22 	 avg: 0.9770992366412213 	 count: 9344 	 MRR: 0.815930042013435
k: 23 	 avg: 0.9777266548154345 	 count: 9350 	 MRR: 0.8159573210644878
k: 24 	 avg: 0.9783540729896476 	 count: 9356 	 MRR: 0.8159834634884134
k: 25 	 avg: 0.9786677820767542 	 count: 9359 	 MRR: 0.8159960118518976
k: 26 	 avg: 0.9792952002509673 	 count: 9365 	 MRR: 0.8160201433201366
k: 27 	 avg: 0.9799226184251804 	 count: 9371 	 MRR: 0.8160433810302926
k: 28 	 avg: 0.980236327512287 	 count: 9374 	 MRR: 0.8160545849262607
k: 29 	 avg: 0.9804454669036913 	 count: 9376 	 MRR: 0.8160617966294125
k: 30 	 avg: 0.9808637456865 	 count: 9380 	 MRR: 0.8160757392555061

# MS Marco

# Fuzzy Join (small)

In [12]:
file = "small_imdb_fuzzy"

bm25 = pd.read_pickle(f"{path}/dev_{file}_argsort_indices.pkl")

supervision = f'/lfs/1/sahaana/enrichment/data/{file}/supervision_test.pkl'
supervision = pd.read_pickle(supervision)
supervision

      FUZZY_ID     tconst
40000    40000  tt1181484
40001    40001  tt1181484
40002    40002  tt1181484
40003    40003  tt1181484
40004    40004  tt1181484
...        ...        ...
49995    49995  tt2014359
49996    49996  tt2014359
49997    49997  tt2014359
49998    49998  tt2014359
49999    49999  tt2014359

[10000 rows x 2 columns]

In [13]:
for k in range(1,31):
    avg, count, MRR, results, MRR_results = bm25_imdb_fuzzy_recall(bm25, supervision, k=k)
    print(f"k: {k} \t avg: {avg} \t count: {count} \t MRR: {MRR}")

k: 1 	 avg: 0.8635 	 count: 8635 	 MRR: 0.8635
k: 2 	 avg: 0.8811 	 count: 8811 	 MRR: 0.8723
k: 3 	 avg: 0.889 	 count: 8890 	 MRR: 0.8749333333333333
k: 4 	 avg: 0.8937 	 count: 8937 	 MRR: 0.8761083333333334
k: 5 	 avg: 0.8988 	 count: 8988 	 MRR: 0.8771283333333333
k: 6 	 avg: 0.903 	 count: 9030 	 MRR: 0.8778283333333333
k: 7 	 avg: 0.9052 	 count: 9052 	 MRR: 0.8781426190476191
k: 8 	 avg: 0.9076 	 count: 9076 	 MRR: 0.8784426190476191
k: 9 	 avg: 0.9102 	 count: 9102 	 MRR: 0.878731507936508
k: 10 	 avg: 0.9127 	 count: 9127 	 MRR: 0.8789815079365079
k: 11 	 avg: 0.9142 	 count: 9142 	 MRR: 0.8791178715728716
k: 12 	 avg: 0.9158 	 count: 9158 	 MRR: 0.879251204906205
k: 13 	 avg: 0.9174 	 count: 9174 	 MRR: 0.8793742818292818
k: 14 	 avg: 0.9184 	 count: 9184 	 MRR: 0.8794457104007104
k: 15 	 avg: 0.9193 	 count: 9193 	 MRR: 0.8795057104007105
k: 16 	 avg: 0.9205 	 count: 9205 	 MRR: 0.8795807104007104
k: 17 	 avg: 0.9212 	 count: 9212 	 MRR: 0.8796218868712986
k: 18 	 avg: 0.9221 	 count: 9221 	 MRR: 0.8796718868712986
k: 19 	 avg: 0.9233 	 count: 9233 	 MRR: 0.8797350447660356
k: 20 	 avg: 0.9238 	 count: 9238 	 MRR: 0.8797600447660354
k: 21 	 avg: 0.9245 	 count: 9245 	 MRR: 0.8797933780993688
k: 22 	 avg: 0.9253 	 count: 9253 	 MRR: 0.8798297417357326
k: 23 	 avg: 0.9261 	 count: 9261 	 MRR: 0.8798645243444282
k: 24 	 avg: 0.9267 	 count: 9267 	 MRR: 0.879889524344428
k: 25 	 avg: 0.9277 	 count: 9277 	 MRR: 0.8799295243444282
k: 26 	 avg: 0.9281 	 count: 9281 	 MRR: 0.8799449089598125
k: 27 	 avg: 0.9291 	 count: 9291 	 MRR: 0.8799819459968498
k: 28 	 avg: 0.9296 	 count: 9296 	 MRR: 0.8799998031397068
k: 29 	 avg: 0.9299 	 count: 9299 	 MRR: 0.880010147967293
k: 30 	 avg: 0.9301 	 count: 9301 	 MRR: 0.8800168146339596

# Fuzzy Join (hard)

In [16]:
file = "hard_imdb_fuzzy"

bm25 = pd.read_pickle(f"{path}/dev_{file}_argsort_indices.pkl")

supervision = f'/lfs/1/sahaana/enrichment/data/{file}/supervision_test.pkl'
supervision = pd.read_pickle(supervision)
supervision

      FUZZY_ID     tconst
40000    40000  tt0196156
40001    40001  tt0196156
40002    40002  tt0196156
40003    40003  tt0196156
40004    40004  tt0196156
...        ...        ...
49995    49995  tt2084021
49996    49996  tt2084021
49997    49997  tt2084021
49998    49998  tt2084021
49999    49999  tt2084021

[10000 rows x 2 columns]

In [17]:
for k in range(1,31):
    avg, count, MRR, results, MRR_results = bm25_imdb_fuzzy_recall(bm25, supervision, k=k)
    print(f"k: {k} \t avg: {avg} \t count: {count} \t MRR: {MRR}")

k: 1 	 avg: 0.6444 	 count: 6444 	 MRR: 0.6444
k: 2 	 avg: 0.6818 	 count: 6818 	 MRR: 0.6631
k: 3 	 avg: 0.6993 	 count: 6993 	 MRR: 0.6689333333333333
k: 4 	 avg: 0.7106 	 count: 7106 	 MRR: 0.6717583333333333
k: 5 	 avg: 0.7186 	 count: 7186 	 MRR: 0.6733583333333334
k: 6 	 avg: 0.7251 	 count: 7251 	 MRR: 0.6744416666666667
k: 7 	 avg: 0.7303 	 count: 7303 	 MRR: 0.6751845238095239
k: 8 	 avg: 0.7352 	 count: 7352 	 MRR: 0.6757970238095239
k: 9 	 avg: 0.7379 	 count: 7379 	 MRR: 0.6760970238095239
k: 10 	 avg: 0.7412 	 count: 7412 	 MRR: 0.6764270238095238
k: 11 	 avg: 0.7438 	 count: 7438 	 MRR: 0.6766633874458874
k: 12 	 avg: 0.7463 	 count: 7463 	 MRR: 0.6768717207792208
k: 13 	 avg: 0.7485 	 count: 7485 	 MRR: 0.6770409515484516
k: 14 	 avg: 0.7512 	 count: 7512 	 MRR: 0.6772338086913087
k: 15 	 avg: 0.7529 	 count: 7529 	 MRR: 0.677347142024642
k: 16 	 avg: 0.7549 	 count: 7549 	 MRR: 0.677472142024642
k: 17 	 avg: 0.7563 	 count: 7563 	 MRR: 0.6775544949658185
k: 18 	 avg: 0.7578 	 count: 7578 	 MRR: 0.6776378282991518
k: 19 	 avg: 0.7591 	 count: 7591 	 MRR: 0.6777062493517834
k: 20 	 avg: 0.7603 	 count: 7603 	 MRR: 0.6777662493517834
k: 21 	 avg: 0.7617 	 count: 7617 	 MRR: 0.6778329160184501
k: 22 	 avg: 0.7627 	 count: 7627 	 MRR: 0.6778783705639045
k: 23 	 avg: 0.7639 	 count: 7639 	 MRR: 0.6779305444769481
k: 24 	 avg: 0.7653 	 count: 7653 	 MRR: 0.6779888778102814
k: 25 	 avg: 0.7658 	 count: 7658 	 MRR: 0.6780088778102814
k: 26 	 avg: 0.7662 	 count: 7662 	 MRR: 0.6780242624256659
k: 27 	 avg: 0.7677 	 count: 7677 	 MRR: 0.6780798179812216
k: 28 	 avg: 0.7681 	 count: 7681 	 MRR: 0.6780941036955074
k: 29 	 avg: 0.769 	 count: 7690 	 MRR: 0.6781251381782659
k: 30 	 avg: 0.7699 	 count: 7699 	 MRR: 0.678155138178266

In [18]:
1

1

# Deepmatcher

In [38]:
datasets = {0:"abt_buy_exp_data", 
            1:"amazon_google_exp_data", 
            2:"beer_exp_data", 
            3:"company_exp_data", 
            4:"dblp_acm_exp_data", 
            5:"dblp_scholar_exp_data", 
            6:"dirty_dblp_acm_exp_data", 
            7:"dirty_dblp_scholar_exp_data", 
            8:"dirty_itunes_amazon_exp_data", 
            9:"dirty_walmart_amazon_exp_data", 
            10:"fodors_zagat_exp_data", 
            11:"itunes_amazon_exp_data", 
            12:"walmart_amazon_exp_data"}

In [43]:
for idx in datasets:
    file = datasets[idx]
    bm25 = pd.read_pickle(f"{path}/{file}_argsort_indices.pkl")
    supervision = f'/lfs/1/sahaana/enrichment/data/deepmatcher/{file}/supervision_test.pkl'
    supervision = pd.read_pickle(supervision)
    
    print(file)
    for k in range(1,15):
        avg, count, MRR, results, MRR_results = bm25_deepmatcher_recall(bm25, supervision, k=k)
        print(f"k: {k} \t avg: {avg} \t count: {count} \t MRR: {MRR}")
    print()
    print()

abt_buy_exp_data
k: 1 	 avg: 0.7580645161290323 	 count: 0.6844660194174758 	 MRR: 0.7193877551020408
k: 2 	 avg: 0.47352941176470587 	 count: 0.7815533980582524 	 MRR: 0.5897435897435896
k: 3 	 avg: 0.36796536796536794 	 count: 0.8252427184466019 	 MRR: 0.5089820359281437
k: 4 	 avg: 0.3076923076923077 	 count: 0.8543689320388349 	 MRR: 0.4524421593830335
k: 5 	 avg: 0.26548672566371684 	 count: 0.8737864077669902 	 MRR: 0.4072398190045249
k: 6 	 avg: 0.2362924281984334 	 count: 0.8786407766990292 	 MRR: 0.3724279835390947
k: 7 	 avg: 0.2211652794292509 	 count: 0.9029126213592233 	 MRR: 0.3553008595988539
k: 8 	 avg: 0.2070874861572536 	 count: 0.9077669902912622 	 MRR: 0.33724075743913434
k: 9 	 avg: 0.19484536082474227 	 count: 0.9174757281553398 	 MRR: 0.32142857142857145
k: 10 	 avg: 0.18568665377176016 	 count: 0.9320388349514563 	 MRR: 0.3096774193548387
k: 11 	 avg: 0.17791970802919707 	 count: 0.9466019417475728 	 MRR: 0.2995391705069124
k: 12 	 avg: 0.17115551694178974 	 count: 0.9563106796116505 	 MRR: 0.290346352247605
k: 13 	 avg: 0.1665264928511354 	 count: 0.9611650485436893 	 MRR: 0.2838709677419355
k: 14 	 avg: 0.16311475409836065 	 count: 0.9660194174757282 	 MRR: 0.2791023842917251


amazon_google_exp_data
k: 1 	 avg: 0.640625 	 count: 0.7008547008547008 	 MRR: 0.6693877551020407
k: 2 	 avg: 0.46172248803827753 	 count: 0.8247863247863247 	 MRR: 0.5920245398773006
k: 3 	 avg: 0.3806921675774135 	 count: 0.8931623931623932 	 MRR: 0.5338441890166028
k: 4 	 avg: 0.32872503840245776 	 count: 0.9145299145299145 	 MRR: 0.4836158192090396
k: 5 	 avg: 0.2945945945945946 	 count: 0.9316239316239316 	 MRR: 0.44763860369609854
k: 6 	 avg: 0.2762022194821208 	 count: 0.9572649572649573 	 MRR: 0.4287081339712918
k: 7 	 avg: 0.2545045045045045 	 count: 0.9658119658119658 	 MRR: 0.4028520499108734
k: 8 	 avg: 0.2359081419624217 	 count: 0.9658119658119658 	 MRR: 0.37919463087248323
k: 9 	 avg: 0.2232055063913471 	 count: 0.9700854700854701 	 MRR: 0.36290967226219023
k: 10 	 avg: 0.2131455399061033 	 count: 0.9700854700854701 	 MRR: 0.3494996150885296
k: 11 	 avg: 0.20670897552130554 	 count: 0.9743589743589743 	 MRR: 0.3410620792819746
k: 12 	 avg: 0.19964973730297722 	 count: 0.9743589743589743 	 MRR: 0.3313953488372093
k: 13 	 avg: 0.19273034657650043 	 count: 0.9743589743589743 	 MRR: 0.32180663373323926
k: 14 	 avg: 0.18673218673218672 	 count: 0.9743589743589743 	 MRR: 0.31340206185567004


beer_exp_data
k: 1 	 avg: 0.875 	 count: 1.0 	 MRR: 0.9333333333333333
k: 2 	 avg: 0.7 	 count: 1.0 	 MRR: 0.8235294117647058
k: 3 	 avg: 0.6363636363636364 	 count: 1.0 	 MRR: 0.7777777777777778
k: 4 	 avg: 0.5384615384615384 	 count: 1.0 	 MRR: 0.7000000000000001
k: 5 	 avg: 0.5 	 count: 1.0 	 MRR: 0.6666666666666666
k: 6 	 avg: 0.5 	 count: 1.0 	 MRR: 0.6666666666666666
k: 7 	 avg: 0.4827586206896552 	 count: 1.0 	 MRR: 0.6511627906976745
k: 8 	 avg: 0.4666666666666667 	 count: 1.0 	 MRR: 0.6363636363636364
k: 9 	 avg: 0.4666666666666667 	 count: 1.0 	 MRR: 0.6363636363636364
k: 10 	 avg: 0.4375 	 count: 1.0 	 MRR: 0.6086956521739131
k: 11 	 avg: 0.4375 	 count: 1.0 	 MRR: 0.6086956521739131
k: 12 	 avg: 0.42424242424242425 	 count: 1.0 	 MRR: 0.5957446808510638
k: 13 	 avg: 0.42424242424242425 	 count: 1.0 	 MRR: 0.5957446808510638
k: 14 	 avg: 0.4117647058823529 	 count: 1.0 	 MRR: 0.5833333333333334


company_exp_data
k: 1 	 avg: 0.9837715027588445 	 count: 0.5374113475177305 	 MRR: 0.6951037725031534
k: 2 	 avg: 0.9536931818181819 	 count: 0.5952127659574468 	 MRR: 0.7329694323144104
k: 3 	 avg: 0.9297355062783863 	 count: 0.6170212765957447 	 MRR: 0.7417670254715975
k: 4 	 avg: 0.9076335877862596 	 count: 0.6324468085106383 	 MRR: 0.7454545454545455
k: 5 	 avg: 0.8892970854763654 	 count: 0.6437943262411348 	 MRR: 0.7468888203229455
k: 6 	 avg: 0.8762199476315163 	 count: 0.6526595744680851 	 MRR: 0.748094705822579
k: 7 	 avg: 0.8643356643356643 	 count: 0.6574468085106383 	 MRR: 0.7468277945619335
k: 8 	 avg: 0.8528069374714742 	 count: 0.6625886524822695 	 MRR: 0.7457593294751547
k: 9 	 avg: 0.8419405320813772 	 count: 0.6677304964539007 	 MRR: 0.7447839414614853
k: 10 	 avg: 0.8329303143548032 	 count: 0.6718085106382978 	 MRR: 0.7437432525272353
k: 11 	 avg: 0.8223755119637853 	 count: 0.6764184397163121 	 MRR: 0.7422901060414437
k: 12 	 avg: 0.8117447530209879 	 count: 0.6789007092198581 	 MRR: 0.7394033021145119
k: 13 	 avg: 0.8023764853033146 	 count: 0.6824468085106383 	 MRR: 0.7375682667433171
k: 14 	 avg: 0.7926503797988093 	 count: 0.6845744680851064 	 MRR: 0.7346589287413187


dblp_acm_exp_data
k: 1 	 avg: 0.9543478260869566 	 count: 0.9887387387387387 	 MRR: 0.9712389380530975
k: 2 	 avg: 0.7717770034843205 	 count: 0.9977477477477478 	 MRR: 0.8703339882121808
k: 3 	 avg: 0.6804915514592934 	 count: 0.9977477477477478 	 MRR: 0.8091324200913242
k: 4 	 avg: 0.6049046321525886 	 count: 1.0 	 MRR: 0.7538200339558574
k: 5 	 avg: 0.5670498084291188 	 count: 1.0 	 MRR: 0.723716381418093
k: 6 	 avg: 0.5336538461538461 	 count: 1.0 	 MRR: 0.6959247648902821
k: 7 	 avg: 0.5085910652920962 	 count: 1.0 	 MRR: 0.6742596810933941
k: 8 	 avg: 0.4841875681570338 	 count: 1.0 	 MRR: 0.6524614254224834
k: 9 	 avg: 0.46884899683210135 	 count: 1.0 	 MRR: 0.6383896477354422
k: 10 	 avg: 0.44984802431610943 	 count: 1.0 	 MRR: 0.6205450733752621
k: 11 	 avg: 0.4344422700587084 	 count: 1.0 	 MRR: 0.6057298772169167
k: 12 	 avg: 0.4220532319391635 	 count: 1.0 	 MRR: 0.5935828877005348
k: 13 	 avg: 0.40771349862258954 	 count: 1.0 	 MRR: 0.5792563600782779
k: 14 	 avg: 0.39361702127659576 	 count: 1.0 	 MRR: 0.5648854961832062


dblp_scholar_exp_data
k: 1 	 avg: 0.9262295081967213 	 count: 0.4224299065420561 	 MRR: 0.5802310654685494
k: 2 	 avg: 0.825511432009627 	 count: 0.6411214953271028 	 MRR: 0.7217254076801685
k: 3 	 avg: 0.7662942271880819 	 count: 0.7691588785046729 	 MRR: 0.7677238805970149
k: 4 	 avg: 0.7226219024780176 	 count: 0.8448598130841122 	 MRR: 0.7789745799224471
k: 5 	 avg: 0.6742857142857143 	 count: 0.8822429906542056 	 MRR: 0.7643724696356275
k: 6 	 avg: 0.6387607119314437 	 count: 0.905607476635514 	 MRR: 0.7491302667182065
k: 7 	 avg: 0.6172993154947106 	 count: 0.9271028037383178 	 MRR: 0.7411281285020546
k: 8 	 avg: 0.5986881335718545 	 count: 0.9383177570093458 	 MRR: 0.7309792500910083
k: 9 	 avg: 0.5803673938002296 	 count: 0.9448598130841122 	 MRR: 0.7190611664295875
k: 10 	 avg: 0.5638179800221975 	 count: 0.9495327102803738 	 MRR: 0.7075208913649024
k: 11 	 avg: 0.550321199143469 	 count: 0.9607476635514018 	 MRR: 0.6997957794417972
k: 12 	 avg: 0.5418410041841004 	 count: 0.9682242990654205 	 MRR: 0.6948356807511736
k: 13 	 avg: 0.5306122448979592 	 count: 0.9719626168224299 	 MRR: 0.6864686468646866
k: 14 	 avg: 0.5183714001986097 	 count: 0.9757009345794393 	 MRR: 0.6770428015564203


dirty_dblp_acm_exp_data
k: 1 	 avg: 0.9564270152505446 	 count: 0.9887387387387387 	 MRR: 0.9723145071982282
k: 2 	 avg: 0.7664359861591695 	 count: 0.9977477477477478 	 MRR: 0.8669275929549902
k: 3 	 avg: 0.6753048780487805 	 count: 0.9977477477477478 	 MRR: 0.8054545454545455
k: 4 	 avg: 0.6127247579529738 	 count: 0.9977477477477478 	 MRR: 0.7592116538131963
k: 5 	 avg: 0.5694087403598972 	 count: 0.9977477477477478 	 MRR: 0.7250409165302782
k: 6 	 avg: 0.5462392108508015 	 count: 0.9977477477477478 	 MRR: 0.7059760956175299
k: 7 	 avg: 0.5217903415783275 	 count: 0.9977477477477478 	 MRR: 0.6852281515854602
k: 8 	 avg: 0.501131221719457 	 count: 0.9977477477477478 	 MRR: 0.6671686746987951
k: 9 	 avg: 0.48156182212581344 	 count: 1.0 	 MRR: 0.6500732064421669
k: 10 	 avg: 0.46589716684155297 	 count: 1.0 	 MRR: 0.6356478167501789
k: 11 	 avg: 0.4444444444444444 	 count: 1.0 	 MRR: 0.6153846153846153
k: 12 	 avg: 0.4306498545101843 	 count: 1.0 	 MRR: 0.6020338983050848
k: 13 	 avg: 0.4188679245283019 	 count: 1.0 	 MRR: 0.5904255319148936
k: 14 	 avg: 0.4062214089661482 	 count: 1.0 	 MRR: 0.5777488614183475


dirty_dblp_scholar_exp_data
k: 1 	 avg: 0.9259259259259259 	 count: 0.4205607476635514 	 MRR: 0.5784061696658097
k: 2 	 avg: 0.8181818181818182 	 count: 0.6392523364485981 	 MRR: 0.7177334732423925
k: 3 	 avg: 0.767097966728281 	 count: 0.7757009345794392 	 MRR: 0.7713754646840147

k: 4 	 avg: 0.7209856915739269 	 count: 0.8476635514018691 	 MRR: 0.779209621993127
k: 5 	 avg: 0.6747851002865329 	 count: 0.8803738317757009 	 MRR: 0.7639902676399027
k: 6 	 avg: 0.6492042440318302 	 count: 0.9149532710280374 	 MRR: 0.7595034910783554
k: 7 	 avg: 0.6159105034182722 	 count: 0.9261682242990654 	 MRR: 0.7398282941396044
k: 8 	 avg: 0.5925487876995861 	 count: 0.9364485981308411 	 MRR: 0.7258239768199929
k: 9 	 avg: 0.5747583854462763 	 count: 0.9448598130841122 	 MRR: 0.7147401908801697
k: 10 	 avg: 0.5583058305830583 	 count: 0.9485981308411215 	 MRR: 0.7029085872576177
k: 11 	 avg: 0.5464247598719317 	 count: 0.9570093457943926 	 MRR: 0.6956521739130436
k: 12 	 avg: 0.5348117586384734 	 count: 0.9691588785046729 	 MRR: 0.6892655367231638
k: 13 	 avg: 0.5239053850025164 	 count: 0.9728971962616823 	 MRR: 0.6810598626104023
k: 14 	 avg: 0.5140601874691663 	 count: 0.9738317757009346 	 MRR: 0.6729092670326122


dirty_itunes_amazon_exp_data
k: 1 	 avg: 1.0 	 count: 0.4074074074074074 	 MRR: 0.5789473684210525
k: 2 	 avg: 0.9411764705882353 	 count: 0.5925925925925926 	 MRR: 0.7272727272727272
k: 3 	 avg: 0.84 	 count: 0.7777777777777778 	 MRR: 0.8076923076923077
k: 4 	 avg: 0.84 	 count: 0.7777777777777778 	 MRR: 0.8076923076923077
k: 5 	 avg: 0.84 	 count: 0.7777777777777778 	 MRR: 0.8076923076923077
k: 6 	 avg: 0.7241379310344828 	 count: 0.7777777777777778 	 MRR: 0.75
k: 7 	 avg: 0.7241379310344828 	 count: 0.7777777777777778 	 MRR: 0.75
k: 8 	 avg: 0.7241379310344828 	 count: 0.7777777777777778 	 MRR: 0.75
k: 9 	 avg: 0.7 	 count: 0.7777777777777778 	 MRR: 0.7368421052631577
k: 10 	 avg: 0.7 	 count: 0.7777777777777778 	 MRR: 0.7368421052631577
k: 11 	 avg: 0.65625 	 count: 0.7777777777777778 	 MRR: 0.711864406779661
k: 12 	 avg: 0.5833333333333334 	 count: 0.7777777777777778 	 MRR: 0.6666666666666666
k: 13 	 avg: 0.5526315789473685 	 count: 0.7777777777777778 	 MRR: 0.6461538461538462
k: 14 	 avg: 0.525 	 count: 0.7777777777777778 	 MRR: 0.6268656716417911


dirty_walmart_amazon_exp_data
k: 1 	 avg: 0.5081967213114754 	 count: 0.8031088082901554 	 MRR: 0.6224899598393574
k: 2 	 avg: 0.3405940594059406 	 count: 0.8911917098445595 	 MRR: 0.4928366762177651
k: 3 	 avg: 0.2783661119515885 	 count: 0.9533678756476683 	 MRR: 0.43091334894613587
k: 4 	 avg: 0.23901808785529716 	 count: 0.9585492227979274 	 MRR: 0.3826266804550155
k: 5 	 avg: 0.21511627906976744 	 count: 0.9585492227979274 	 MRR: 0.35137701804368465
k: 6 	 avg: 0.19640971488912354 	 count: 0.9637305699481865 	 MRR: 0.32631578947368417
k: 7 	 avg: 0.18111002921129504 	 count: 0.9637305699481865 	 MRR: 0.3049180327868853
k: 8 	 avg: 0.17017383348581885 	 count: 0.9637305699481865 	 MRR: 0.2892690513219285
k: 9 	 avg: 0.16216216216216217 	 count: 0.9637305699481865 	 MRR: 0.27761194029850744
k: 10 	 avg: 0.15448504983388706 	 count: 0.9637305699481865 	 MRR: 0.26628489620615603
k: 11 	 avg: 0.1496 	 count: 0.9689119170984456 	 MRR: 0.2591822591822592
k: 12 	 avg: 0.14462490332559938 	 count: 0.9689119170984456 	 MRR: 0.25168236877523553
k: 13 	 avg: 0.13986537023186238 	 count: 0.9689119170984456 	 MRR: 0.24444444444444446
k: 14 	 avg: 0.13619810633648943 	 count: 0.9689119170984456 	 MRR: 0.23882503192848017


fodors_zagat_exp_data
k: 1 	 avg: 0.5116279069767442 	 count: 1.0 	 MRR: 0.676923076923077
k: 2 	 avg: 0.3384615384615385 	 count: 1.0 	 MRR: 0.5057471264367815
k: 3 	 avg: 0.2558139534883721 	 count: 1.0 	 MRR: 0.40740740740740744
k: 4 	 avg: 0.2268041237113402 	 count: 1.0 	 MRR: 0.36974789915966383
k: 5 	 avg: 0.205607476635514 	 count: 1.0 	 MRR: 0.34108527131782945
k: 6 	 avg: 0.19469026548672566 	 count: 1.0 	 MRR: 0.3259259259259259
k: 7 	 avg: 0.1864406779661017 	 count: 1.0 	 MRR: 0.3142857142857143
k: 8 	 avg: 0.17886178861788618 	 count: 1.0 	 MRR: 0.30344827586206896
k: 9 	 avg: 0.16666666666666666 	 count: 1.0 	 MRR: 0.2857142857142857
k: 10 	 avg: 0.15942028985507245 	 count: 1.0 	 MRR: 0.27499999999999997
k: 11 	 avg: 0.1527777777777778 	 count: 1.0 	 MRR: 0.26506024096385544
k: 12 	 avg: 0.14473684210526316 	 count: 1.0 	 MRR: 0.2528735632183908
k: 13 	 avg: 0.1375 	 count: 1.0 	 MRR: 0.2417582417582418
k: 14 	 avg: 0.13580246913580246 	 count: 1.0 	 MRR: 0.2391304347826087


itunes_amazon_exp_data
k: 1 	 avg: 0.9166666666666666 	 count: 0.4074074074074074 	 MRR: 0.5641025641025641
k: 2 	 avg: 0.8421052631578947 	 count: 0.5925925925925926 	 MRR: 0.6956521739130435
k: 3 	 avg: 0.8260869565217391 	 count: 0.7037037037037037 	 MRR: 0.76
k: 4 	 avg: 0.84 	 count: 0.7777777777777778 	 MRR: 0.8076923076923077
k: 5 	 avg: 0.84 	 count: 0.7777777777777778 	 MRR: 0.8076923076923077
k: 6 	 avg: 0.7777777777777778 	 count: 0.7777777777777778 	 MRR: 0.7777777777777778
k: 7 	 avg: 0.75 	 count: 0.7777777777777778 	 MRR: 0.7636363636363638
k: 8 	 avg: 0.7241379310344828 	 count: 0.7777777777777778 	 MRR: 0.75
k: 9 	 avg: 0.7241379310344828 	 count: 0.7777777777777778 	 MRR: 0.75
k: 10 	 avg: 0.7 	 count: 0.7777777777777778 	 MRR: 0.7368421052631577
k: 11 	 avg: 0.6363636363636364 	 count: 0.7777777777777778 	 MRR: 0.7000000000000001
k: 12 	 avg: 0.6 	 count: 0.7777777777777778 	 MRR: 0.6774193548387097
k: 13 	 avg: 0.5833333333333334 	 count: 0.7777777777777778 	 MRR: 0.6666666666666666
k: 14 	 avg: 0.525 	 count: 0.7777777777777778 	 MRR: 0.6268656716417911


walmart_amazon_exp_data
k: 1 	 avg: 0.5111821086261981 	 count: 0.8290155440414507 	 MRR: 0.6324110671936759
k: 2 	 avg: 0.3326923076923077 	 count: 0.8963730569948186 	 MRR: 0.485273492286115
k: 3 	 avg: 0.27095808383233533 	 count: 0.9378238341968912 	 MRR: 0.42044134727061555
k: 4 	 avg: 0.23261694058154236 	 count: 0.9533678756476683 	 MRR: 0.37398373983739835
k: 5 	 avg: 0.20898876404494382 	 count: 0.9637305699481865 	 MRR: 0.34349030470914127
k: 6 	 avg: 0.19179487179487179 	 count: 0.9689119170984456 	 MRR: 0.3202054794520548
k: 7 	 avg: 0.17998075072184794 	 count: 0.9689119170984456 	 MRR: 0.30357142857142855
k: 8 	 avg: 0.16862037871956717 	 count: 0.9689119170984456 	 MRR: 0.2872503840245776
k: 9 	 avg: 0.15942028985507245 	 count: 0.9689119170984456 	 MRR: 0.273792093704246
k: 10 	 avg: 0.15153970826580226 	 count: 0.9689119170984456 	 MRR: 0.2620882971268395
k: 11 	 avg: 0.1476826394344069 	 count: 0.9740932642487047 	 MRR: 0.2564802182810368
k: 12 	 avg: 0.14231642694928084 	 count: 0.9740932642487047 	 MRR: 0.24834874504623514
k: 13 	 avg: 0.13752743233357717 	 count: 0.9740932642487047 	 MRR: 0.24102564102564097
k: 14 	 avg: 0.13361762615493958 	 count: 0.9740932642487047 	 MRR: 0.235